// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL
{
    public partial class GetTickerInfoResult
    {
        public string Id { get; set; }
        public string StockName { get; set; }
        public decimal LatestPrice { get; set; }
        public DateTime LatestPriceDate { get; set; }
        public string Ticker { get; set; }
    }
}
